version: "3.9"
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    ports:
      - '5556:5432'
    volumes:
      - db:/var/lib/posgres/data/
volumes:
  db:
    driver: local